### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Locksdsc** [Michael-Gatmaitan/michael-gatmaitan-webportfolio#1]
Hey can you help me on omo music

**Comment by Michael-Gatmaitan** [comment]
> Hey can you help me on omo music

Sure, what's the problem?

**Comment by Locksdsc** [comment]
uh i actually just cloned your repo and used it on netlify but it doesn't build the site i need to make a music website for project at school :/

**Comment by Michael-Gatmaitan** [comment]
I have some problem with that repo, i accidetally created a new branch and it destroy the updated version of code. I'm not sure if that's the cause of your problem , try it again.
